name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file packages/backend/Dockerfile --tag mikesteam-backstage:$(date +%s)

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: setup
      run: yarn install && yarn tsc && yarn build:backend
    - name: build-image
      run: cd packages/backend && yarn build-image